### ISSUE TITLE
validate that every relation has a relation type

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#333] opened 2022-06-21 22:04 UTC
not sure if this has already been fixed, but the ICA instance has relationships without a relation type. i think saving these should be disallowed.

example:

`https://ica.acdh-dev.oeaw.ac.at/apis/api/relations/personplace/542/`

results in:

```
{
    "url": "https://ica.acdh-dev.oeaw.ac.at/apis/api/relations/personplace/542/",
    "id": 542,
    "review": false,
    "start_date": null,
    "start_start_date": null,
    "start_end_date": null,
    "end_date": null,
    "end_start_date": null,
    "end_end_date": null,
    "start_date_written": null,
    "end_date_written": null,
    "status": "",
    "references": null,
    "notes": null,
    "published": false,
    "source": null,
    "related_person": {
        "id": 540,
        "label": "Kraus, Karl",
        "url": "https://ica.acdh-dev.oeaw.ac.at/apis/api/entities/person/540/"
    },
    "related_place": {
        "id": 541,
        "label": "Jitschin",
        "url": "https://ica.acdh-dev.oeaw.ac.at/apis/api/entities/place/541/"
    },
    "relation_type": null
}
```

other example relations with the same issue: 532, 535, 538, 

note that all of these have `published: false`

**Comment by sennierer** [comment] 2022-06-29 11:30
tested it inlocal instance, its possible to create a relation without a relationtype. Shouldnt be and actually wasnt the case. we need fix that.

**Comment by stefanprobst** [comment] 2022-06-30 10:29
note that this currently also crashes the UI, e.g. https://ica.acdh-dev.oeaw.ac.at/apis/entities/entity/person/540/detail

looking at the response from https://ica.acdh-dev.oeaw.ac.at/apis/api/entities/person/540/ there's a empty relation type

**Comment by stefanprobst** [comment] 2022-07-10 14:43
@steffres are you working on this?

**Comment by gregorpirgie** [comment] 2022-07-13 13:59
seems to be linked to sentry issue [#APIS-PMB-M ](https://sentry.acdh-dev.oeaw.ac.at/organizations/acdhch-sentry/issues/142/) and issue #325

**Comment by steffres** [comment] 2022-07-14 13:14
I've added a check to relation class if any foreign keys are null. This check happens on save call and not on the field definition itself as it might be necessary to temporarily allow None values in memory.

However this does not fix the currently missing `relation_type` of existing objects. These need to be manually re-written.

As for issue https://github.com/acdh-oeaw/apis-core/issues/325 I can query succesfully https://pmb.acdh.oeaw.ac.at/apis/api/relations/placeevent/?format=json%2Bnet&limit=51%22 though I don't understand how these issues are supposed to be connected.

relevant commit:  
https://github.com/acdh-oeaw/apis-core/commit/6864fe822fb8738802ff4989405c28479d6ccdfb

**Comment by stefanprobst** [comment] 2022-07-14 13:46
just fyi, `curl "https://pmb.acdh.oeaw.ac.at/apis/api/relations/placeevent/?format=json%2Bnet&limit=51"` is totally still returning 500 for me.

**Comment by steffres** [comment] 2022-07-15 06:50
True. When I had curled it I forgot quotation marks and the `&` escaped into bash. 

@gregorpirgie  how do you think this issue is related to https://github.com/acdh-oeaw/apis-core/issues/325 ? In that sentry https://sentry.acdh-dev.oeaw.ac.at/organizations/acdhch-sentry/issues/142/?project=3 I don't see anything that points to a empty `relation_type`? There the error is `'NoneType' object is not subscriptable` indicating that something of the line `d2["source"]["url"].split("/")[-3].title()` is None and an index of it is being accessed. From that code context I don't see anything pointing to `relation_type` though.

**Comment by sennierer** [comment] 2022-07-20 15:17
ok, so I reproduced the error locally. And it is caused by `PlaceEvent.objects.get(id=35228)` not having assigned a `related_place`. Before 6864fe822fb8738802ff4989405c28479d6ccdfb added by @steffres it was possible (at least in the ORM) to set related entities in relations to None (reproduced that in a4787ba2497670d1664419e84b93778ddc9836eb). So the cause of the problem is fixed with @steffres fix, but the problem persist in the data. I will add a fix to leave out relations that do not contain source and target, but we should also fix the data.

**Closed** 2022-07-20 15:26 UTC
Labels: bug

**Comment by sennierer** [comment] 2022-07-20 15:28
please note (@stefanprobst ) that this fix leaves out the broken entries from the db. so `curl "https://pmb.acdh.oeaw.ac.at/apis/api/relations/placeevent/?format=json%2Bnet&limit=51" wont break the API anymore, but until the broken entry is fixed return only 50 entries instead of 51

**Comment by sennierer** [comment] 2022-07-20 16:19
the fix mentioned above is deployed on our instances

**Comment by stefanprobst** [comment] 2022-07-20 16:53
can you quickly clarify what has been fixed, and what has not yet?

- https://ica.acdh-dev.oeaw.ac.at/apis/entities/entity/person/540/detail still returns 500
- `curl https://ica.acdh-dev.oeaw.ac.at/apis/api/relations/personplace/542/` still returns an entity with `relation_type: null`
- `curl "https://ica.acdh-dev.oeaw.ac.at/apis/api/relations/personplace/?limit=10" | jq '.results[].relation_type'` still shows 4 out of the first 10 results have `relation_type: null`

**Comment by sennierer** [comment] 2022-07-20 17:07
yes, validation is now in place, but there is still invalid data
