### ISSUE TITLE
Cannot enter date

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#144] opened 2019-10-17 14:03 UTC
I try to enter this:

> <1943>um 1943

in the end field of

https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/4427/edit

but it creates an error 500

**Comment by csae8092** [comment] 2019-10-18 08:45
@steffres  could you take a look, pmb runs on latest apis-core code (https://github.com/acdh-oeaw/apis-core/commit/5aab9f9c29ab39fdf5d03ea78fb0ddda13b26bf1) and latest apis-webpage-base code (https://github.com/acdh-oeaw/apis-webpage-base/commit/3482b9c53c36d1789d9544abd3c4b4fad1cbf1b9) please also have a look at the applications dedicated settings file (server.py) which you can find on the server. Thanks!

**Comment by sennierer** [comment] 2019-10-18 10:24
this is by intention. you need to enter "um 1943<1943-01-01>"
The angel brackets notation should be after the string, not at the beginning. And in angel brackets you need to specify a complete iso-date.

**Comment by steffres** [comment] 2019-10-21 08:25
As Sennierer said, the date within the angle brackets must be an iso-date (YYYY-MM-DD), however the order of its appearance doesn't matter, be it in the beginning, middle or end of the textual input.

The error is thrown because "<1943>um 1943" does not contain a correct iso date. However it should not crash the application, I will look into this.

Also if you want to express that the date is located somewhere within a whole year, then you can just write "1943" and it will interpret it as a date range, spanning 1943-1-1 until 1943-12-31. Same for a whole month, e.g. "1943-2" or "2.1943" will be interpreted as 1943-2-1 until 1943-2-28.

**Comment by steffres** [comment] 2019-10-22 09:03
I could not reproduce the 500 error on my local instance. The commits are the same as the production instance is running on as Peter communicated, i.e. apis_core: 5aab9f9 and apis_webpage_base: 3482b9c
And I tried to put in various invalid and valid date formats into wherever possible.

@martinantonmueller please let me know if you come across this error again when inputting something date related. Until this should happen again I can't investigate anything unfortunately.

**Comment by martinantonmueller** [comment] 2019-10-22 09:39
I can reproduce the error 500 just by doing what I stated in my opening post.

**Comment by steffres** [comment] 2019-10-22 13:19
On pmb@minerva in /home/pmb/pmb/apis-core the local git repo is on commit 2790757 from the 8.10. so simply my changes are not integrated yet in the production instance.
@csae8092 what local git repo did you mean when you stated before that it runs on commit 5aab9f9 ?

**Comment by csae8092** [comment] 2019-10-22 15:21
@steffres good question ..., anyhow I now (for sure) pulled apis-core for production version. Btw, we can check the actual commit by our awesome project-info endpoint https://pmb.acdh.oeaw.ac.at/project-info/

**Comment by steffres** [comment] 2019-10-23 08:22
Ah, cool, thanks for this link info. 

I tested various date inputs and it seems to work. Unless @martinantonmueller experiences something otherwise, I'll close this ticket.

**Closed by steffres** 2019-10-23 08:22 UTC
