### ISSUE TITLE
Autocomplete endpoint should return APIS id

### ISSUE THREAD

**Issue by skurzinz** [acdh-oeaw/apis-core#337] opened 2022-07-07 09:59 UTC
@sviatoplok is doing markup using the OfficeEntityPlugin, which does queries such as

> https://mpr.acdh.oeaw.ac.at/apis/entities/autocomplete/place/?term=praha&q=praha&_type=query

The endpoint in this case returns the GeoNames id first, this then gets inserted into the word documents through the plugin, which is unintended. Please make the endpoint return the APIS id if the entry is present in the database.

**Comment by skurzinz** [comment] 2022-08-29 09:48
Expected behaviour: 
always return APIS-id first, even if there are multiple URIs associated with the entity.

**Comment by sviatoplok** [comment] 2022-08-29 09:55
This problem still remains, as does the connected merge problem #341 .

**Comment by gregorpirgie** [comment] 2022-08-31 08:29
Update: created a merge request with potential fix for this issue. Fix re-orders the autocomplete suggestions to return entries with apis-id first (but still in original order, i.e. the first apis-id-entry first, then the second apis-id-entry, etc. and then all other suggestions in their original order).

**Comment by gregorpirgie** [comment] 2022-08-31 09:30
Ok, after discussing it with Matthias just now, I see now that the root of the issue is different as to how it appeared in my local instance, working on a fix now, as the merge request won't resolve this specific case. This should then indeed fix issue #341 also.

**Comment by sviatoplok** [comment] 2022-09-01 13:39
also happens in the case of https://mpr.acdh.oeaw.ac.at/entity/3166

**Comment by sviatoplok** [comment] 2022-09-01 13:43
ditto https://mpr.acdh.oeaw.ac.at/entity/1436

**Comment by sviatoplok** [comment] 2022-09-05 09:12
> Ok, after discussing it with Matthias just now, I see now that the root of the issue is different as to how it appeared in my local instance, working on a fix now, as the merge request won't resolve this specific case. This should then indeed fix issue #341 also.

How is the fix coming?

**Comment by sviatoplok** [comment] 2022-10-05 08:30
Have you found out what the root of the problem is in the meantime, @gregorpirgie ?

**Comment by sennierer** [comment] 2022-10-25 11:49
this should be fixed in latest

**Closed by sennierer** 2022-10-25 11:49 UTC
Labels: enhancement

**Comment by sviatoplok** [comment] 2022-11-07 12:21
Now, some of the problematic entries are not being displayed in the autocomplete list of the entity plugin.

This happens, e.g. with Prag and Ungarn.

Were there maybe changes made when bulk-updating?

Not sure whether I should reopen this.

**Comment by sviatoplok** [comment] 2022-11-07 13:06
And I just created this URL: 

http://https//mpr.acdh.oeaw.ac.at/apis/api2/entity/3286/

Shouldn't that be https://mpr.acdh.oeaw.ac.at/apis/api2/entity/3286/

**Comment by sviatoplok** [comment] 2022-11-08 11:01
Right now, Hungary is not being returned by the entity plugIn at all, although it is in the MPR database.

Might this be about the place entities? It works fine in institutions...

**Comment by sviatoplok** [comment] 2022-11-08 11:06
The same goes for the *merge into* dialog.

Is this maybe a hint where the problem comes from?

![grafik](https://user-images.githubusercontent.com/46528983/200548701-4b2f87e1-38c4-45d2-8d40-01b1e45050dd.png)

**Comment by skurzinz** [comment] 2022-11-08 11:41
> Right now, Hungary is not being returned by the entity plugIn at all, although it is in the MPR database.

Confirming: https://mpr.acdh.oeaw.ac.at/entity/1398/ is not returned in https://mpr.acdh.oeaw.ac.at/apis/entities/autocomplete/place/?term=ungarn&q=ungarn&_type=query

**Comment by sviatoplok** [comment] 2022-11-08 14:14
Same with Reichsregierung, deutsches Reich [https://mpr.acdh.oeaw.ac.at/entity/10744](https://mpr.acdh.oeaw.ac.at/entity/10744)

**Comment by sennierer** [comment] 2022-11-11 11:26
@richardhadden could this be related to the recent changes to the autocomplete?

**Comment by sennierer** [comment] 2022-11-11 11:49
@richardhadden correctly mentioned that https://mpr.acdh.oeaw.ac.at/entity/1398/ does not contain its own uri. I will update the URIs in MPR this afternoon. lets check after that again.

**Comment by sviatoplok** [comment] 2022-11-11 11:50
Btw, mostly, the autocomplete works fine now, thanks for that! I could even find Żywiec today when I typed in Saybusch .

**Comment by skurzinz** [comment] 2022-11-11 11:52
> @richardhadden correctly mentioned that https://mpr.acdh.oeaw.ac.at/entity/1398/ does not contain its own uri. I will update the URIs in MPR this afternoon. lets check after that again.

Ah that explains the erratic behaviour. Very old entities are affected as IDs were only lateron included as URIs. Thx to @sennierer for fixing this database-wise soon :)

**Comment by sennierer** [comment] 2022-11-11 14:49
added the missing uris to the db and - at least the problem with "ungarn" - is resolved. Please reopen if other problems occur.

**Comment by sviatoplok** [comment] 2022-11-11 14:53
Many thanks, I already managed to merge, so it works.
